### ISSUE TITLE
demo.py 单张图测试，调节--image_short_side参数，设置1280没问题，再设置其他的报错

### ISSUE THREAD

**Issue by wuzuowuyou** [MhLiao/DB#119]
Traceback (most recent call last):
  File "demo.py", line 148, in <module>
    main()
  File "demo.py", line 43, in main
    Demo(experiment, experiment_args, cmd=args).inference(args['image_path'], args['visualize'])
  File "demo.py", line 137, in inference
    pred = model.forward(batch, training=False)
  File "/data_1/Yang/project/2019/project/DB/20200120_git/0121_2/DB-master/structure/model.py", line 56, in forward
    pred = self.model(data, training=self.training)
  File "/data_1/Yang/software_install/Anaconda1105/envs/DB_cuda10_2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/DB_cuda10_2/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/data_1/Yang/software_install/Anaconda1105/envs/DB_cuda10_2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data_1/Yang/project/2019/project/DB/20200120_git/0121_2/DB-master/structure/model.py", line 19, in forward
    return self.decoder(self.backbone(data), *args, **kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/DB_cuda10_2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data_1/Yang/project/2019/project/DB/20200120_git/0121_2/DB-master/decoders/seg_detector.py", line 124, in forward
    out4 = self.up5(in5) + in4  # 1/16
RuntimeError: The size of tensor a (94) must match the size of tensor b (93) at non-singleton dimension 3

运行的指令：
CUDA_VISIBLE_DEVICES=0 python demo.py /data_1/0project/DB/20200120_git/0121_2/DB-master/experiments/seg_detector/merge_data_resnet50_deform_thre-SRC.yaml --resume /data_1/0project/DB/20200120_git/0121_2/DB-master/myfile/model_epoch_4_minibatch_120000  --box_thresh 0.35 --visualize --image_path 111.jpg --image_short_side 1480

图片大小是1200*1600的.
设置1280*2不报错，这个尺寸有什么讲究的吗

**Comment by MhLiao** [comment]
@wuzuowuyou 需要是32的整数倍
