### ISSUE TITLE
编译问题：error: command ':/usr/local/cuda-9.0:/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1

### ISSUE THREAD

**Issue by Tian14267** [MhLiao/DB#164]
作者你好，各位小伙伴们好。我在编译的时候，遇到以下问题：
‘running build_ext
building 'deform_conv_cuda' extension
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/src
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/hj/anaconda3/lib/python3.5/site-packages/torch/include -I/home/hj/anaconda3/lib/python3.5/site-packages/torch/include/torch/csrc/api/include -I/home/hj/anaconda3/lib/python3.5/site-packages/torch/include/TH -I/home/hj/anaconda3/lib/python3.5/site-packages/torch/include/THC -I:/usr/local/cuda-9.0:/usr/local/cuda-9.0/include -I/home/hj/anaconda3/include/python3.5m -c src/deform_conv_cuda.cpp -o build/temp.linux-x86_64-3.5/src/deform_conv_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
:/usr/local/cuda-9.0:/usr/local/cuda-9.0/bin/nvcc -I/home/hj/anaconda3/lib/python3.5/site-packages/torch/include -I/home/hj/anaconda3/lib/python3.5/site-packages/torch/include/torch/csrc/api/include -I/home/hj/anaconda3/lib/python3.5/site-packages/torch/include/TH -I/home/hj/anaconda3/lib/python3.5/site-packages/torch/include/THC -I:/usr/local/cuda-9.0:/usr/local/cuda-9.0/include -I/home/hj/anaconda3/include/python3.5m -c src/deform_conv_cuda_kernel.cu -o build/temp.linux-x86_64-3.5/src/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
unable to execute ':/usr/local/cuda-9.0:/usr/local/cuda-9.0/bin/nvcc': No such file or directory
error: command ':/usr/local/cuda-9.0:/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1’

我的cuda是9.0版本的，pytorch是1.0版本的。两个版本应该是匹配的（运行其他代码正常）。请问这个问题该怎么解决？

**Comment by Tian14267** [comment]
@MhLiao

**Comment by 15926273249** [comment]
pytorch版本和cuda版本不适配

**Comment by Tian14267** [comment]
@15926273249 你确定？我的其他代码，都能正常运行。

**Comment by 15926273249** [comment]
我之前搜索说的是这个问题，我直接换了环境

**Comment by Tian14267** [comment]
你说的换环境是指什么？更换cuda还是pytorch？还是其他？

**Comment by 15926273249** [comment]
用的是cuda10.2, python3.6, pytorch1.0

**Comment by Tian14267** [comment]
累哭。。。真不想更新cuda版本。太麻烦了。。。你那个问题解决了不

**Comment by 15926273249** [comment]
没有呢，自从换了镜像之后各种问题

**Comment by Tian14267** [comment]
如果真是版本问题，那就懒得折腾了。不过感觉不像是版本问题。。。

**Comment by Tian14267** [comment]
作者你好，请问下您能解决我这个问题吗？或者说，基于cuda9.0的配置，该用什么样的配置可以完成你这个算法？ @MhLiao

**Comment by 15926273249** [comment]
你测试或是训练icdar2015的数据集有没有出现
Traceback (most recent call last):
  File "eval.py", line 193, in <module>
    main()
  File "eval.py", line 77, in main
    experiment = Configurable.construct_class_from_config(experiment_args)
  File "/DBNet/DB/concern/config.py", line 130, in construct_class_from_config
    return cls(**args)
  File "/DBNet/DB/experiment.py", line 96, in __init__
    self.load_all(**kwargs)
  File "/DBNet/DB/concern/config.py", line 143, in load_all
    self.load(name, **kwargs)
  File "/DBNet/DB/concern/config.py", line 151, in load
    (kwargs[state_name], cmd)))
  File "/DBNet/DB/concern/config.py", line 164, in create_member_from_config
    return cls(**args, cmd=cmd)
  File "/DBNet/DB/experiment.py", line 37, in __init__
    self.load_all(**kwargs)
  File "/DBNet/DB/concern/config.py", line 143, in load_all
    self.load(name, **kwargs)
  File "/DBNet/DB/concern/config.py", line 151, in load
    (kwargs[state_name], cmd)))
  File "/DBNet/DB/concern/config.py", line 164, in create_member_from_config
    return cls(**args, cmd=cmd)
  File "/DBNet/DB/data/data_loader.py", line 30, in __init__
    self.load_all(**kwargs)
  File "/DBNet/DB/concern/config.py", line 143, in load_all
    self.load(name, **kwargs)
  File "/DBNet/DB/concern/config.py", line 151, in load
    (kwargs[state_name], cmd)))
  File "/DBNet/DB/concern/config.py", line 164, in create_member_from_config
    return cls(**args, cmd=cmd)
  File "/DBNet/DB/data/image_dataset.py", line 34, in __init__
    self.get_all_samples()
  File "/DBNet/DB/data/image_dataset.py", line 58, in get_all_samples
    self.targets = self.load_ann()
  File "/DBNet/DB/data/image_dataset.py", line 75, in load_ann
    poly = np.array(list(map(float, line[:8]))).reshape((-1, 2)).tolist()
ValueError: could not convert string to float: '###'

**Comment by Tian14267** [comment]
笔记：遇到我那个问题，不需要升级cuda，原因是cuda环境变量的问题。直接export CUDA_HOME=/usr/local/cuda-9.0就可以了。

**Comment by Tian14267** [comment]
我直接用TD_TR数据集训练的。你先试试这个数据集怎么样 @15926273249

**Comment by 15926273249** [comment]
我也是用这个数据集训练的，但是测试其他数据集都有上面的问题

**Comment by Tian14267** [comment]
我还没用在其他数据集中。回头我试试。

**Comment by 15926273249** [comment]
好的，要是可以的话再交流

**Comment by Tian14267** [comment]
我的在 icdar2015 数据集上训练正常
![image](https://user-images.githubusercontent.com/27938135/82528545-91508280-9b6b-11ea-82f8-fcb9e77385da.png)
@15926273249

**Comment by 15926273249** [comment]
可以看一下你的数据的格式吗，还有标签的格式，或者能给我发一下你训练的数据集吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tian14267"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 下午2:02
收件人:&nbsp;"MhLiao/DB"<DB@noreply.github.com&gt;;
抄送:&nbsp;"921825229"<921825229@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MhLiao/DB] 编译问题：error: command ':/usr/local/cuda-9.0:/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1 (#164)





 
我的在 icdar2015 数据集上训练正常
 
 @15926273249

**Comment by Tian14267** [comment]
可以，也就是把数据给到就行了。配置啥的没动。batch调小一点（内存不够）
![image](https://user-images.githubusercontent.com/27938135/82529951-b692c000-9b6e-11ea-9058-ebac4f7a57a3.png)

**Comment by 15926273249** [comment]
我好像是数据标签格式有问题，跟下载的train_gts对应不上，可以把你训练的数据发给我吗





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tian14267"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 下午2:25
收件人:&nbsp;"MhLiao/DB"<DB@noreply.github.com&gt;;
抄送:&nbsp;"921825229"<921825229@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MhLiao/DB] 编译问题：error: command ':/usr/local/cuda-9.0:/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1 (#164)





 
可以，也就是把数据给到就行了。配置啥的没动。batch调小一点（内存不够）

**Comment by Tian14267** [comment]
留下你的联系方式，发给你

**Comment by 15926273249** [comment]
邮箱是921825229@qq.com


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tian14267"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 下午2:32
收件人:&nbsp;"MhLiao/DB"<DB@noreply.github.com&gt;;
抄送:&nbsp;"921825229"<921825229@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MhLiao/DB] 编译问题：error: command ':/usr/local/cuda-9.0:/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1 (#164)





 
留下你的联系方式，发给你

**Comment by Tian14267** [comment]
已发

**Comment by 15926273249** [comment]
好的，已经收到，谢谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tian14267"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 下午2:35
收件人:&nbsp;"MhLiao/DB"<DB@noreply.github.com&gt;;
抄送:&nbsp;"921825229"<921825229@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MhLiao/DB] 编译问题：error: command ':/usr/local/cuda-9.0:/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1 (#164)





 
已发

**Comment by Tian14267** [comment]
你 TD 数据的训练测试效果怎么样？我的很烂

**Comment by 15926273249** [comment]
我用TD90%-93%差不多





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tian14267"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 下午2:43
收件人:&nbsp;"MhLiao/DB"<DB@noreply.github.com&gt;;
抄送:&nbsp;"921825229"<921825229@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MhLiao/DB] 编译问题：error: command ':/usr/local/cuda-9.0:/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1 (#164)





 
你 TD 数据的训练测试效果怎么样？我的很烂

**Comment by Tian14267** [comment]
你的效果为啥这么好。我直观感受就很烂了。

**Comment by 15926273249** [comment]
完全没有改什么，结果跟github上差不多，你是不是改了什么


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tian14267"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 下午2:47
收件人:&nbsp;"MhLiao/DB"<DB@noreply.github.com&gt;;
抄送:&nbsp;"921825229"<921825229@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MhLiao/DB] 编译问题：error: command ':/usr/local/cuda-9.0:/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1 (#164)





 
你的效果为啥这么好。我直观感受就很烂了。

**Comment by Tian14267** [comment]
我加你QQ，我们QQ聊吧

**Comment by 15926273249** [comment]
要不微信吧，我电脑没QQ, 微信号T921825229





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tian14267"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 下午2:49
收件人:&nbsp;"MhLiao/DB"<DB@noreply.github.com&gt;;
抄送:&nbsp;"921825229"<921825229@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MhLiao/DB] 编译问题：error: command ':/usr/local/cuda-9.0:/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1 (#164)





 
我加你QQ，我们QQ聊吧

**Comment by Tian14267** [comment]
已添加，望通过。或者提供其他沟通方式

**Comment by WayoSunny** [comment]
请问你们的问题解决了吗？
我在训练阶段运行代码
`CUDA_VISIBLE_DEVICES=4,5 python train.py /data2/user1/DB-master/experiments/seg_detector/ic15_resnet50_deform_thre.yaml --num_gpus 2`
在epoch0的时候遇到bug：
`error in modulated_deformable_col2im_coord_cuda: invalid device function
error in modulated_deformable_col2im_cuda: invalid device function
/opt/conda/conda-bld/pytorch_1579022027550/work/aten/src/THCUNN/BCECriterion.cu:57: void bce_updateOutput_no_reduce_functor<Dtype, Acctype>::operator()(const Dtype *, const Dtype *, Dtype *) [with Dtype = float, Acctype = float]: block: [49,0,0], thread: [223,0,0] Assertion `*input >= 0. && *input <= 1.` failed.
`
然后
`RuntimeError: transform: failed to synchronize: cudaErrorAssert: device-side assert triggered
`
不知道是我的数据标注有问题..还是环境有问题。。
我的是pytorch=1.4    cudatoolkit=10.1  python=3.6
求解惑，谢谢！！！

**Comment by WayoSunny** [comment]
请问你们的问题解决了吗？
我在训练阶段运行代码
`CUDA_VISIBLE_DEVICES=4,5` python train.py /data2/user1/DB-master/experiments/seg_detector/ic15_resnet50_deform_thre.yaml --num_gpus 2`
在epoch0的时候遇到bug：
`error in modulated_deformable_col2im_coord_cuda: invalid device function` `error in modulated_deformable_col2im_cuda: invalid device function` `/opt/conda/conda-bld/pytorch_1579022027550/work/aten/src/THCUNN/BCECriterion.cu:57: void bce_updateOutput_no_reduce_functor<Dtype, Acctype>::operator()(const Dtype *, const Dtype *, Dtype *) [with Dtype = float, Acctype = float]: block: [49,0,0], thread: [223,0,0] Assertion *input >= 0. && *input <= 1.failed.`
然后
`RuntimeError: transform: failed to synchronize: cudaErrorAssert: device-side assert triggered`

不知道是我的数据标注有问题..还是环境有问题。。
我的是pytorch=1.4 cudatoolkit=10.1 python=3.6
求解惑，谢谢！！！

**Comment by WayoSunny** [comment]
请问你们的问题解决了吗？
我在训练阶段运行代码
`CUDA_VISIBLE_DEVICES=4,5 python train.py /data2/user1/DB-master/experiments/seg_detector/ic15_resnet50_deform_thre.yaml --num_gpus 2`

在epoch0的时候遇到bug：
`error in modulated_deformable_col2im_coord_cuda: invalid device function `
`error in modulated_deformable_col2im_cuda: invalid device function`
` /opt/conda/conda-bld/pytorch_1579022027550/work/aten/src/THCUNN/BCECriterion.cu:57: void bce_updateOutput_no_reduce_functor<Dtype, Acctype>::operator()(const Dtype *, const Dtype *, Dtype *) [with Dtype = float, Acctype = float]: block: [49,0,0], thread: [223,0,0] Assertion *input >= 0. && *input <= 1.failed.`

然后就。。：
`RuntimeError: transform: failed to synchronize: cudaErrorAssert: device-side assert triggered`

不知道是我的数据标注有问题..还是环境有问题。。
我的是pytorch=1.4 cudatoolkit=10.1 python=3.6
求解惑，谢谢！！！

**Comment by Ffmydy** [comment]
@MhLiao @Tian14267 @15926273249 我也遇到这个问题，我想确认一下，真的是版本问题吗

**Comment by light1003** [comment]
same error torch=1.6 cuda=10.1 python=3.7

**Comment by Akshay-Ijantkar** [comment]
@Tian14267 @15926273249 @WayoSunny  Same issue here

**Comment by xray1111** [comment]
@Tian14267 请问你用cuda9.0编译dcn的问题解决了吗，怎么解决的？谢谢！

**Comment by duydangg** [comment]
someone please help me with this error: 
```
gcc: error: src/deform_conv_cuda.cpp: No such file or directory
error: command 'gcc' failed with exit status 1
```

**Comment by volkov-maxim** [comment]
Got the same error when running a demo for icdar2015.
`$ python demo.py experiments/seg_detector/ic15_resnet50_deform_thre.yaml --imageataset/probation/X00016469620.jpg --resume models/ic15_resnet50 --box_thresh 0.7
...
ValueError: could not convert string to float...`

Solved with converting all txt files in _datasets\icdar2015\train_gts_ from **UTF-8-BOM** to **UTF-8**

Python3 script:
`
from pathlib import Path

PATH = r'<path to datasets\icdar2015\train_gts>'

p = Path(PATH)

for bom_file in p.glob('*.txt'):
    s = open(bom_file, mode='r', encoding='utf-8-sig').read()
    open(bom_file, mode='w', encoding='utf-8').write(s)
`

**Comment by WayoSunny** [comment]
请问正确的pytorch和python版本是什么啊？

**Comment by volkov-maxim** [comment]
Python 3.7.6
torch 1.7.1+cuda

**Comment by DanLiu0623** [comment]
> 
> 
> 请问你们的问题解决了吗？
> 我在训练阶段运行代码
> `CUDA_VISIBLE_DEVICES=4,5 python train.py /data2/user1/DB-master/experiments/seg_detector/ic15_resnet50_deform_thre.yaml --num_gpus 2`
> 
> 在epoch0的时候遇到bug：
> `error in modulated_deformable_col2im_coord_cuda: invalid device function `
> `error in modulated_deformable_col2im_cuda: invalid device function`
> ` /opt/conda/conda-bld/pytorch_1579022027550/work/aten/src/THCUNN/BCECriterion.cu:57: void bce_updateOutput_no_reduce_functor<Dtype, Acctype>::operator()(const Dtype *, const Dtype *, Dtype *) [with Dtype = float, Acctype = float]: block: [49,0,0], thread: [223,0,0] Assertion *input >= 0. && *input <= 1.failed.`
> 
> 然后就。。：
> `RuntimeError: transform: failed to synchronize: cudaErrorAssert: device-side assert triggered`
> 
> 不知道是我的数据标注有问题..还是环境有问题。。
> 我的是pytorch=1.4 cudatoolkit=10.1 python=3.6
> 求解惑，谢谢！！！
请问您这个问题解决了吗？我也是遇到这个问题

**Comment by DanLiu0623** [comment]
@WayoSunny 请问你的问题解决了吗？我也是遇到这个问题

**Comment by Purewhiter** [comment]
Maybe its the problem of the path. You should export CUDA_HOME=/usr/local/cuda , do not add "$CUDA_HOME:", or the file path will become ":/usr/local/cuda/bin/nvcc" and cause an error

**Comment by MaryFeng824** [comment]
> Maybe its the problem of the path. You should export CUDA_HOME=/usr/local/cuda , do not add "$CUDA_HOME:", or the file path will become ":/usr/local/cuda/bin/nvcc" and cause an error

yes,ooo,thanks.This works for me,to solve the install  detectron2 can not find nvcc .( but first  my order 'nvcc -V' is work,just can not build detectron2).do not forget 'source  ~/.bashrc' to make change work.

**Comment by MaryFeng824** [comment]
> Maybe its the problem of the path. You should export CUDA_HOME=/usr/local/cuda , do not add "$CUDA_HOME:", or the file path will become ":/usr/local/cuda/bin/nvcc" and cause an error

yes,ooo,thanks.This works for me,to solve the install  detecctron2 can not find nvcc .( but first  my order 'nvcc -V' is work,just can not build detectron2).do not forget 'source  ~/.bashrc' to make change work.
