### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'data'

### ISSUE THREAD

**Issue by deepseek** [MhLiao/DB#17]
```
home@home-desktop:~/p9/DB/datasets/total_text$ tree -L 1
.
├── test_gts
├── test_images
├── test_list.txt
├── train_gts
├── train_images
└── train_list.txt
```
```
(db) home@home-desktop:~/p9/DB$ python eval.py experiments/seg_detector/totaltext_resnet18_deform_thre.yaml --resume ./modelz/totaltext_resnet18 --polygon --box_thresh 0.6
./datasets/total_text/
[INFO] [2019-12-04 19:50:45,447] Resuming from ./modelz/totaltext_resnet18
[INFO] [2019-12-04 19:50:45,496] Resumed from ./modelz/totaltext_resnet18
  0%|                                                                                                                                                                       | 0/300 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "eval.py", line 193, in <module>
    main()
  File "eval.py", line 79, in main
    Eval(experiment, experiment_args, cmd=args, verbose=args['verbose']).eval(args['visualize'])
  File "eval.py", line 176, in eval
    pred = model.forward(batch, training=False)
  File "/home/home/p9/DB/structure/model.py", line 56, in forward
    pred = self.model(data, training=self.training)
  File "/home/home/anaconda3/envs/db/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/home/anaconda3/envs/db/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/home/anaconda3/envs/db/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/home/anaconda3/envs/db/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/home/anaconda3/envs/db/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/home/anaconda3/envs/db/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/home/anaconda3/envs/db/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'data'

Segmentation fault
```

**Comment by ws-lin** [comment]
the same error

**Comment by ws-lin** [comment]
I set it to work on just one gpu

**Comment by liangkaihuan** [comment]
I changed model.py(line:56) to 
`        if self.training:`
`            pred = self.model(data, training=self.training)`
`        else:`
`            pred = self.model(data)`
and solved the problem.

**Comment by MhLiao** [comment]
@deepseek I think @ws-lin is right. Could you please try to use `CUDA_VISIBLE_DEVICES=0` in the command.

**Comment by deepseek** [comment]
@ws-lin What code values did you change to solve this?
@liangkaihuan Upload your modified `model.py` here so i can test.

**Comment by deepseek** [comment]
@MhLiao `CUDA_VISIBLE_DEVICES=0` allows to continue the process, but the end is "Segmentation fault", and in `results` folder nothing is recognized.

```
(db) home@home-desktop:~/p9/DB$ CUDA_VISIBLE_DEVICES=0 python eval.py experiments/seg_detector/totaltext_resnet18_deform_thre.yaml --resume ./modelz/totaltext_resnet18 --polygon --box_thresh 0.6
./datasets/total_text/
[INFO] [2019-12-05 20:11:06,534] Resuming from ./modelz/totaltext_resnet18
[INFO] [2019-12-05 20:11:06,563] Resumed from ./modelz/totaltext_resnet18
100%|██████████████████████████████████████████████████████████████████████████████████████| 300/300 [00:10<00:00, 27.78it/s]
[INFO] [2019-12-05 20:11:17,641] precision : 0.000000 (300)
[INFO] [2019-12-05 20:11:17,641] recall : 0.000000 (300)
[INFO] [2019-12-05 20:11:17,641] fmeasure : 0.000000 (1)
Segmentation fault
```

**Comment by liangkaihuan** [comment]
I tested `CUDA_VISIBLE_DEVICES=0` without modifying code, and the `forward() missing` error can also be solved. I think `Segmentation fault` in your case may come from incorrect compilation of deformable convolution.

**Comment by deepseek** [comment]
@liangkaihuan Thanks for the hint,
I found the solution, the issue was  caused because I had `CUDA Version 10.0.130`, while @MhLiao tutorial had `cudatoolkit=10.1`.
In my case, the solution was tot use `cudatoolkit=10.0`
Thanks all

**Comment by leedewdew** [comment]
use CUDA_VISIBLE_DEVICES=0 can't always solve this problem when run the demo.
It still tells "TypeError: forward() missing 1 required positional argument: 'data'" . 
Are there some other problems?

**Comment by leedewdew** [comment]
> use CUDA_VISIBLE_DEVICES=0 can't always solve this problem when run the demo.
> It still tells "TypeError: forward() missing 1 required positional argument: 'data'" .
> Are there some other problems?

After hundreds of time trying, I find the issue is "CUDA_VISIBLE_DEVICES=0" doesn't take effect in my centos, while add one line of "os.environ["CUDA_VISIBLE_DEVICES"] = '3'" finally saved me.

**Comment by zhouyuangan** [comment]
The problem is here: [DataParallel doesn't properly handle kwargs](https://github.com/pytorch/pytorch/issues/31460)

**Comment by qiaoyaya2011** [comment]
@deepseek it doesn't work.  cuda version is equal  cudatoolkit version.
