### ISSUE TITLE
Training for OpenCV TextDetectionModel_DB

### ISSUE THREAD

**Issue by atagulmert** [MhLiao/DB#231]
Hi, I'm trying to train a new custom DB model and possibly convert it to ONNX format to use it with OpenCV. I'm already using pre-trained weights which are given [here](https://drive.google.com/drive/folders/1qzNCHfUJOS0NEUOIKn69eCtxdlNPpWbq). I've also managed to train and get good results with eval.py and demo.py. Then I tried to convert that model file to ONNX using _torch.onnx.export._ Here is how I did it after loading the model and weights;

`dummy_input = torch.randn(1, 3, None, None, requires_grad=True)
torch.onnx.export(model, dummy_input, "db.onnx")`

This results in an error
`RuntimeError: hasSpecialCase INTERNAL ASSERT FAILED at /pytorch/torch/csrc/jit/passes/alias_analysis.cpp:300, please report a bug to PyTorch. We don't have an op for aten::to but it isn't a special case. (analyzeImpl at /pytorch/torch/csrc/jit/passes/alias_analysis.cpp:300)`

To fix this in [model.py(line 39)](https://github.com/MhLiao/DB/blob/6f208690cbb1a84e259f45fff465fad4ae5a6751/structure/model.py#L39) I have commented out paralleling of model.
`...
self.model = BasicModel(args)
        # for loading models
        # self.model = parallelize(self.model, distributed, local_rank)
        self.criterion = SegDetectorLossBuilder(...`

After that it exports an onnx file without an error. When I try to import that model to opencv and do inference, I get these error;

`opencv/modules/core/src/matrix.cpp:806: error: (-215:Assertion failed) m.dims <= 2 in function 'Mat'`

I'm not sure if the problem is occuring when converting to onnx. Problem might be opencv related. Are there any guidelines to train/use our own DB models with opencv?

**Comment by tranducanhbk** [comment]
Hi Mert Atagül!

Coulde you show CODE for convert pytorch to ONNX.
Many thanks you

**Comment by atagulmert** [comment]
I used pytorch's function torch.onnx.export which you can find details [here](https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html). To be more specific I have modified the demo.py to create the model and load my weights into it. [Added a few lines here](https://github.com/MhLiao/DB/blob/4e341f7c07005fe5cccac8f4042c03f0ef4424cb/demo.py#L125)
`def inference(self, image_path, visualize=False):
        self.init_torch_tensor()
        model = self.init_model()
        self.resume(model, self.model_path)
        dummy_input = torch.randn(1, 3, 736, 992, requires_grad=True)
        all_matircs = {}
        model.eval()
        torch.onnx.export(model, dummy_input, "db.onnx")
        batch = dict()
        batch['filename'] = [image_path]
        img, original_shape = self.load_image(image_path)
        batch['shape'] = [original_shape]
        with torch.no_grad():
            batch['image'] = img
            print(img.shape)
            pred = model.forward(batch, training=False)
            output = self.structure.representer.represent(batch, pred, is_output_polygon=self.args['polygon']) 
            if not os.path.isdir(self.args['result_dir']):
                os.mkdir(self.args['result_dir'])
            self.format_output(batch, output)

            if visualize and self.structure.visualizer:
                vis_image = self.structure.visualizer.demo_visualize(image_path, output)
                cv2.imwrite(os.path.join(self.args['result_dir'], image_path.split('/')[-1].split('.')[0]+'.jpg'), vis_image)`

**Comment by tranducanhbk** [comment]
Thank you your quick reply.
Maybe we have to train with non paralelnize mode. I trained with parallel mode and then load  with non parallel to inference the results is bad

**Comment by atagulmert** [comment]
I doubt that data paralleling effects inference results. It would be great if someone who achieved training and transporting that model to openCV could help.

**Comment by tranducanhbk** [comment]
When i try using your code to convert torch to onnx i got error like below:
![Capture](https://user-images.githubusercontent.com/54969565/115492979-12892b80-a28d-11eb-91c9-3d6e3bee1f8b.JPG)
But when i using https://github.com/Media-Smart/volksdep it is ok. Do you know why?

**Comment by yiran-THU** [comment]
@MhLiao    I also encounter this problem,  can you help us?

**Comment by yiran-THU** [comment]
@atagulmert @tranducanhbk

**Comment by yiran-THU** [comment]
Have you solve this problem?

**Comment by atagulmert** [comment]
Unfortunately no I didn't and currently working on something else. But I'm still keen to learn if this is possible.

**Comment by yiran-THU** [comment]
@atagulmert 

Have change DCN module?
When I follow your method,  get following error:
`RuntimeError: ONNX export failed: Couldn't export Python operator ModulatedDeformConvFunction`

**Comment by gigasurgeon** [comment]
I am getting this error when exporting to ONNX

```
verbose: True
Initializing log dir for workspace/SegDetectorModel-seg_detector/deformable_resnet50/L1BalanceCELoss
/vmdata/amitsingh/workspace/z2/dataset_download_from_deeplabel_and_convert_to_TD500_format/DBnet_TD500_format_dataset
Resumed from /vmdata/amitsingh/workspace/z2/DB/outputs/workspace/DB/SegDetectorModel-seg_detector/deformable_resnet50/L1BalanceCELoss/model/final
Traceback (most recent call last):
  File "convert_to_onnx.py", line 106, in <module>
    main()
  File "convert_to_onnx.py", line 23, in main
    Demo(experiment, experiment_args, cmd=args).inference_2(image_path='/vmdata/amitsingh/workspace/z2/dataset_download_from_deeplabel_and_convert_to_TD500_format/640014a40816ca001e0c45fd/images/6406e37b0816ca001e0ea8ba.jpg')
  File "convert_to_onnx.py", line 86, in inference_2
    torch.onnx.export(model, dummy_input, "db.onnx")
  File "/vmdata/amitsingh/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/vmdata/amitsingh/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/vmdata/amitsingh/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 1115, in _model_to_graph
    graph = _optimize_graph(
  File "/vmdata/amitsingh/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 605, in _optimize_graph
    _C._jit_pass_peephole(graph, True)
IndexError: Argument passed to at() was not in the map.
```
