### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by sinror** [MhLiao/DB#253]
running build_ext
/root/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py:369: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
building 'deform_conv_cuda' extension
gcc -std=gnu99 -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda3/lib/python3.8/site-packages/torch/include -I/root/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/root/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/root/anaconda3/include/python3.8 -c src/deform_conv_cuda.cpp -o build/temp.linux-x86_64-3.8/src/deform_conv_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
In file included from /root/anaconda3/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:140:0,
                 from /root/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /root/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /root/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /root/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                 from /root/anaconda3/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from src/deform_conv_cuda.cpp:4:
/root/anaconda3/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:83:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 ^
/usr/local/cuda-10.2/bin/nvcc -I/root/anaconda3/lib/python3.8/site-packages/torch/include -I/root/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/root/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/root/anaconda3/include/python3.8 -c src/deform_conv_cuda_kernel.cu -o build/temp.linux-x86_64-3.8/src/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -ccbin gcc -std=gnu99 -std=c++14
gcc -std=gnu99: No such file or directory
error: command '/usr/local/cuda-10.2/bin/nvcc' failed with exit status 1

编译的时候出现这种错误 是什么原因？gcc版本5.5

**Comment by sinror** [comment]
这个问题解决了 ，安装了ninja

**Comment by sinror** [comment]
又有新的问题 
running build_ext
building 'deform_conv_cuda' extension
creating /search/odin/daemon/luoxin/DB-master/assets/ops/dcn/build
creating /search/odin/daemon/luoxin/DB-master/assets/ops/dcn/build/temp.linux-x86_64-3.7
creating /search/odin/daemon/luoxin/DB-master/assets/ops/dcn/build/temp.linux-x86_64-3.7/src
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "/root/anaconda3/envs/db_pytorch/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/root/anaconda3/envs/db_pytorch/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/root/anaconda3/envs/db_pytorch/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/root/anaconda3/envs/db_pytorch/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/db_pytorch/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/root/anaconda3/envs/db_pytorch/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/root/anaconda3/envs/db_pytorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/root/anaconda3/envs/db_pytorch/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/root/anaconda3/envs/db_pytorch/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/root/anaconda3/envs/db_pytorch/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/root/anaconda3/envs/db_pytorch/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/root/anaconda3/envs/db_pytorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 538, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/root/anaconda3/envs/db_pytorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1335, in _write_ninja_file_and_compile_objects
    check_compiler_abi_compatibility(compiler)
  File "/root/anaconda3/envs/db_pytorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 282, in check_compiler_abi_compatibility
    if not check_compiler_ok_for_platform(compiler):
  File "/root/anaconda3/envs/db_pytorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 242, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/root/anaconda3/envs/db_pytorch/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/root/anaconda3/envs/db_pytorch/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'g++ -std=gnu++0x']' returned non-zero exit status 1.

**Comment by sinror** [comment]
问题解决了  安装了ninja
