### ISSUE TITLE
Polygon reshaping error from eval.py with ic15_resnet18_deform_thre.yaml

### ISSUE THREAD

**Issue by mattroos** [MhLiao/DB#261]
I'm trying to replicate the evaluation of the ResNet18 model on ICDAR 2015.
```
CUDA_VISIBLE_DEVICES=0 python eval.py experiments/seg_detector/ic15_resnet18_deform_thre.yaml \
--resume ./ic15_resnet18 \
--box_thresh 0.55
```
I get this error from the DataLoader:

```
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/mroos/python_envs/env_torch/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mroos/python_envs/env_torch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mroos/python_envs/env_torch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mroos/Code/DB/data/image_dataset.py", line 100, in __getitem__
    data = data_process(data)
  File "/home/mroos/Code/DB/data/processes/data_process.py", line 9, in __call__
    return self.process(data)
  File "/home/mroos/Code/DB/data/processes/augment_data.py", line 46, in process
    self.may_augment_annotation(aug, data, shape)
  File "/home/mroos/Code/DB/data/processes/augment_data.py", line 72, in may_augment_annotation
    new_polys = np.array([p.x, p.y] for p in keypoints).reshape([-1, 4, 2])
ValueError: cannot reshape array of size 1 into shape (4,2)
```

Any suggestions?

**Comment by mattroos** [comment]
@jiangxiluning I believe your commit from yesterday is causing this, FYI.

**Comment by jiangxiluning** [comment]
sorry about it, i wiil fix it as soon as possible.

**Comment by jiangxiluning** [comment]
@mattroos hi brother, just check this https://github.com/MhLiao/DB/pull/263 .

**Comment by mattroos** [comment]
No problem. It happens. Thanks!

**Comment by gioipv** [comment]
Hello, thank you @jiangxiluning , but i see that.
This commit  https://github.com/MhLiao/DB/pull/263/commits not updated yet on master branch.
https://github.com/MhLiao/DB/blob/master/data/processes/augment_data.py#L72
