### ISSUE TITLE
评估时出错，IndexError: list index out of range

### ISSUE THREAD

**Issue by hhhoushiyu** [MhLiao/DB#37]
你好，感谢你的工作，我在试图评估时报错
`IndexError: list index out of range`
具体如下：
python eval.py experiments/seg_detector/totaltext_resnet50_deform_thre.yaml --resume models/totaltext_resnet50 --polygon --box_thresh 0.6
Traceback (most recent call last):
  File "eval.py", line 193, in <module>
    main()
  File "eval.py", line 77, in main
    experiment = Configurable.construct_class_from_config(experiment_args)
  File "./DB/concern/config.py", line 130, in construct_class_from_config
    return cls(**args)
  File "./DB/experiment.py", line 96, in __init__
    self.load_all(**kwargs)
  File "./DB/concern/config.py", line 143, in load_all
    self.load(name, **kwargs)
  File "./DB/concern/config.py", line 151, in load
    (kwargs[state_name], cmd)))
  File "./DB/concern/config.py", line 164, in create_member_from_config
    return cls(**args, cmd=cmd)
  File "./DB/experiment.py", line 37, in __init__
    self.load_all(**kwargs)
  File "./DB/concern/config.py", line 143, in load_all
    self.load(name, **kwargs)
  File "./DB/concern/config.py", line 151, in load
    (kwargs[state_name], cmd)))
  File "./DB/concern/config.py", line 164, in create_member_from_config
    return cls(**args, cmd=cmd)
  File "./DB/data/data_loader.py", line 29, in __init__
    self.load_all(**kwargs)
  File "./DB/concern/config.py", line 143, in load_all
    self.load(name, **kwargs)
  File "./DB/concern/config.py", line 151, in load
    (kwargs[state_name], cmd)))
  File "./DB/concern/config.py", line 164, in create_member_from_config
    return cls(**args, cmd=cmd)
  File "./DB/data/image_dataset.py", line 33, in __init__
    self.get_all_samples()
  File "./DB/data/image_dataset.py", line 37, in get_all_samples
    with open(self.data_list[i], 'r') as fid:
IndexError: list index out of range

我使用的是python 3.7.5 pytorch 1.3.1 cuda 10.1
请问我该怎么做？

**Comment by MhLiao** [comment]
@hhhoushiyu 我觉得这个错误与安装环境无关，可能跟你的数据集路径或者数据集有关。

**Comment by hhhoushiyu** [comment]
是数据集路径的问题，感谢回复
