### ISSUE TITLE
No module named 'structure.representers.boxes_from_map'

### ISSUE THREAD

**Issue by deepseek** [MhLiao/DB#7]
When running:
```
python eval.py ./experiments/seg_detector/base.yaml --resume ./modelz/totaltext_resnet50 --polygon --box_thresh 0.6

```

I get error:
```
Traceback (most recent call last):
  File "eval.py", line 8, in <module>
    from trainer import Trainer
  File "/home/home/p9/DB/trainer.py", line 6, in <module>
    from experiment import Experiment
  File "/home/home/p9/DB/experiment.py", line 4, in <module>
    from structure.representers import *
  File "/home/home/p9/DB/structure/representers/__init__.py", line 2, in <module>
    from .boxes_from_map import boxes_from_map
ModuleNotFoundError: No module named 'structure.representers.boxes_from_map'
```

**Comment by deepseek** [comment]
@MhLiao the `boxes_from_map` is missing :sunglasses:

**Comment by MhLiao** [comment]
@deepseek I have fixed it now. `boxes_from_map` is not used.

**Comment by deepseek** [comment]
Thanks man
