### ISSUE TITLE
KeyError: 'Experiment'

### ISSUE THREAD

**Issue by deepseek** [MhLiao/DB#8]
```
(db) home@home-desktop:~/p9/DB$ python eval.py ./experiments/seg_detector/base.yaml --resume ./modelz/totaltext_resnet50 --polygon --box_thresh 0.6
Traceback (most recent call last):
  File "eval.py", line 193, in <module>
    main()
  File "eval.py", line 75, in main
    experiment_args = conf.compile(conf.load(args['exp']))['Experiment']
KeyError: 'Experiment'
```
@MhLiao test the code, both `train.py` and `eval.py`

**Comment by MhLiao** [comment]
@deepseek Please do not use the YAML file that contains the keyword of "base".
